version: '3'
services:
    api:
        build: ./
        command: sh -c "knex migrate:latest && knex seed:run && npm run dev"
        restart: always
        ports:
            - 3000:3000
        environment:
            - DB_HOST=db
            - DB_USER=test_user
            - DB_PASS=root
            - DB_NAME=testDb
        volumes:
            - ./index.js:/var/www/html/index.js
            - ./src:/var/www/html/src
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./docker/data:/var/postgresql/data:rw
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=test_user
            - POSTGRES_DB=testDb
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080